### ISSUE TITLE
Flaky AsyncDataCacheTest.ssdWriteOptions

### ISSUE THREAD

**Issue by bikramSingh91** [facebookincubator/velox#11463]
### Bug description

https://github.com/facebookincubator/velox/actions/runs/11710857535/job/32618103540?pr=11451

### System information

fails on github actions

### Relevant logs

```bash
[ RUN      ] AsyncDataCacheTest/AsyncDataCacheTest.ssdWriteOptions/2
I20241106 20:09:48.436640  6767 SsdCache.cpp:45] [SSDCA] SSD cache config: 4 shards, capacity 64.00MB, checkpoint size 3.20MB, file cow ENABLED, checksum ENABLED, read verification ENABLED
W20241106 20:09:48.436792  6767 SsdFile.cpp:880] [SSDCA] Starting shard 0 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_f8HY57/cache0.cpt
W20241106 20:09:48.436939  6767 SsdFile.cpp:880] [SSDCA] Starting shard 1 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_f8HY57/cache1.cpt
W20241106 20:09:48.437089  6767 SsdFile.cpp:880] [SSDCA] Starting shard 2 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_f8HY57/cache2.cpt
W20241106 20:09:48.437232  6767 SsdFile.cpp:880] [SSDCA] Starting shard 3 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_f8HY57/cache3.cpt
W20241106 20:09:48.437348  6767 MemoryArbitrator.cpp:84] Query memory capacity[16.00MB] is set for NOOP arbitrator which has no capacity enforcement
I20241106 20:09:48.449529  6767 SsdCache.cpp:209] [SSDCA] SSD cache is shutting down
I20241106 20:09:48.449584  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 0, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.450917  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.450961  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 1, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.452351  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.452391  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 2, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.455456  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.455497  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 3, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.456686  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.456729  6767 SsdCache.cpp:216] [SSDCA] SSD cache has been shutdown
I20241106 20:09:48.457118  6767 TempDirectoryPath.cpp:29] TempDirectoryPath:: removing all files from /tmp/velox_test_f8HY57
I20241106 20:09:48.457540  6767 SsdCache.cpp:45] [SSDCA] SSD cache config: 4 shards, capacity 64.00MB, checkpoint size 3.20MB, file cow ENABLED, checksum ENABLED, read verification ENABLED
W20241106 20:09:48.457690  6767 SsdFile.cpp:880] [SSDCA] Starting shard 0 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_i2Em0J/cache0.cpt
W20241106 20:09:48.457834  6767 SsdFile.cpp:880] [SSDCA] Starting shard 1 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_i2Em0J/cache1.cpt
W20241106 20:09:48.457985  6767 SsdFile.cpp:880] [SSDCA] Starting shard 2 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_i2Em0J/cache2.cpt
W20241106 20:09:48.458128  6767 SsdFile.cpp:880] [SSDCA] Starting shard 3 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_i2Em0J/cache3.cpt
W20241106 20:09:48.458267  6767 MemoryArbitrator.cpp:84] Query memory capacity[16.00MB] is set for NOOP arbitrator which has no capacity enforcement
I20241106 20:09:48.471318  6767 SsdCache.cpp:209] [SSDCA] SSD cache is shutting down
I20241106 20:09:48.471390  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 0, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.472945  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.472987  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 1, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.473968  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.474007  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 2, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.474915  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.474957  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 3, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.475879  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.475917  6767 SsdCache.cpp:216] [SSDCA] SSD cache has been shutdown
I20241106 20:09:48.476325  6767 TempDirectoryPath.cpp:29] TempDirectoryPath:: removing all files from /tmp/velox_test_i2Em0J
I20241106 20:09:48.476727  6767 SsdCache.cpp:45] [SSDCA] SSD cache config: 4 shards, capacity 64.00MB, checkpoint size 3.20MB, file cow ENABLED, checksum ENABLED, read verification ENABLED
W20241106 20:09:48.476876  6767 SsdFile.cpp:880] [SSDCA] Starting shard 0 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_Snl1I3/cache0.cpt
W20241106 20:09:48.477020  6767 SsdFile.cpp:880] [SSDCA] Starting shard 1 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_Snl1I3/cache1.cpt
W20241106 20:09:48.477175  6767 SsdFile.cpp:880] [SSDCA] Starting shard 2 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_Snl1I3/cache2.cpt
W20241106 20:09:48.477327  6767 SsdFile.cpp:880] [SSDCA] Starting shard 3 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_Snl1I3/cache3.cpt
W20241106 20:09:48.477452  6767 MemoryArbitrator.cpp:84] Query memory capacity[16.00MB] is set for NOOP arbitrator which has no capacity enforcement
I20241106 20:09:48.488456  6767 SsdCache.cpp:209] [SSDCA] SSD cache is shutting down
I20241106 20:09:48.488546  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 0, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.490458  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.490507  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 1, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.491590  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.491631  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 2, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.492802  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.492842  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 3, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.493976  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.494015  6767 SsdCache.cpp:216] [SSDCA] SSD cache has been shutdown
I20241106 20:09:48.494428  6767 TempDirectoryPath.cpp:29] TempDirectoryPath:: removing all files from /tmp/velox_test_Snl1I3
I20241106 20:09:48.494820  6767 SsdCache.cpp:45] [SSDCA] SSD cache config: 4 shards, capacity 64.00MB, checkpoint size 3.20MB, file cow ENABLED, checksum ENABLED, read verification ENABLED
W20241106 20:09:48.494967  6767 SsdFile.cpp:880] [SSDCA] Starting shard 0 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_PHoteI/cache0.cpt
W20241106 20:09:48.495131  6767 SsdFile.cpp:880] [SSDCA] Starting shard 1 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_PHoteI/cache1.cpt
W20241106 20:09:48.495282  6767 SsdFile.cpp:880] [SSDCA] Starting shard 2 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_PHoteI/cache2.cpt
W20241106 20:09:48.495440  6767 SsdFile.cpp:880] [SSDCA] Starting shard 3 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_PHoteI/cache3.cpt
W20241106 20:09:48.495555  6767 MemoryArbitrator.cpp:84] Query memory capacity[16.00MB] is set for NOOP arbitrator which has no capacity enforcement
I20241106 20:09:48.501828 10080 AsyncDataCache.cpp:573] [SSDCA] Limiting SSD save batch to 75 entries
I20241106 20:09:48.501861 10080 AsyncDataCache.cpp:573] [SSDCA] Limiting SSD save batch to 100 entries
I20241106 20:09:48.501874 10080 AsyncDataCache.cpp:573] [SSDCA] Limiting SSD save batch to 99 entries
I20241106 20:09:48.501886 10080 AsyncDataCache.cpp:573] [SSDCA] Limiting SSD save batch to 97 entries
I20241106 20:09:48.502462 10098 SsdFile.cpp:347] [SSDCA] Grow cache file /tmp/velox_test_PHoteI/cache0 to 1 regions (max: 1)
I20241106 20:09:48.503414 10099 SsdFile.cpp:347] [SSDCA] Grow cache file /tmp/velox_test_PHoteI/cache1 to 1 regions (max: 1)
I20241106 20:09:48.503944 10100 SsdFile.cpp:347] [SSDCA] Grow cache file /tmp/velox_test_PHoteI/cache2 to 1 regions (max: 1)
I20241106 20:09:48.506866 10101 SsdFile.cpp:347] [SSDCA] Grow cache file /tmp/velox_test_PHoteI/cache3 to 1 regions (max: 1)
I20241106 20:09:48.507328 10101 SsdCache.cpp:138] [SSDCA] Wrote 681.54KB, 128.19618 bytes/s
I20241106 20:09:48.508594  6767 SsdCache.cpp:209] [SSDCA] SSD cache is shutting down
I20241106 20:09:48.508617  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 0, force: 1 bytesAfterCheckpoint: 250.59KB checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.511464  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 23 cache entries
I20241106 20:09:48.511495  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 1, force: 1 bytesAfterCheckpoint: 73.93KB checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.513278  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 26 cache entries
I20241106 20:09:48.513303  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 2, force: 1 bytesAfterCheckpoint: 220.02KB checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.514882  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 28 cache entries
I20241106 20:09:48.514909  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 3, force: 1 bytesAfterCheckpoint: 137.01KB checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.517082  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 25 cache entries
I20241106 20:09:48.517107  6767 SsdCache.cpp:216] [SSDCA] SSD cache has been shutdown
I20241106 20:09:48.517503  6767 TempDirectoryPath.cpp:29] TempDirectoryPath:: removing all files from /tmp/velox_test_PHoteI
I20241106 20:09:48.517885  6767 SsdCache.cpp:45] [SSDCA] SSD cache config: 4 shards, capacity 64.00MB, checkpoint size 3.20MB, file cow ENABLED, checksum ENABLED, read verification ENABLED
W20241106 20:09:48.518004  6767 SsdFile.cpp:880] [SSDCA] Starting shard 0 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_WAwr3b/cache0.cpt
W20241106 20:09:48.518136  6767 SsdFile.cpp:880] [SSDCA] Starting shard 1 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_WAwr3b/cache1.cpt
W20241106 20:09:48.518285  6767 SsdFile.cpp:880] [SSDCA] Starting shard 2 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_WAwr3b/cache2.cpt
W20241106 20:09:48.518414  6767 SsdFile.cpp:880] [SSDCA] Starting shard 3 without checkpoint, with checksum write enabled, read verification enabled, checkpoint file /tmp/velox_test_WAwr3b/cache3.cpt
W20241106 20:09:48.518517  6767 MemoryArbitrator.cpp:84] Query memory capacity[16.00MB] is set for NOOP arbitrator which has no capacity enforcement
I20241106 20:09:48.519084  6767 AsyncDataCache.cpp:573] [SSDCA] Limiting SSD save batch to 0 entries
/__w/velox/velox/velox/common/caching/tests/AsyncDataCacheTest.cpp:1457: Failure
Expected: (stats.ssdStats->entriesWritten) > (0), actual: 0 vs 0
Google Test trace:
/__w/velox/velox/velox/common/caching/tests/AsyncDataCacheTest.cpp:1443: maxWriteRatio 0, ssdSavableRatio 0.95, minSsdSavableBytes 0, expectedSaveToSsd true
I20241106 20:09:48.526108  6767 SsdCache.cpp:209] [SSDCA] SSD cache is shutting down
I20241106 20:09:48.526175 10102 SsdFile.cpp:347] [SSDCA] Grow cache file /tmp/velox_test_WAwr3b/cache1 to 1 regions (max: 1)
I20241106 20:09:48.526283 10102 SsdCache.cpp:138] [SSDCA] Wrote 100B, 0.013910141 bytes/s
I20241106 20:09:48.626246  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 0, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.628921  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.628968  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 1, force: 1 bytesAfterCheckpoint: 100B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.631106  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 1 cache entries
I20241106 20:09:48.631148  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 2, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.632305  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.632345  6767 SsdFile.cpp:749] [SSDCA] Checkpointing shard 3, force: 1 bytesAfterCheckpoint: 0B checkpointIntervalBytes: 819.20KB
I20241106 20:09:48.633105  6767 SsdFile.cpp:859] [SSDCA] Checkpoint persisted with 0 cache entries
I20241106 20:09:48.633143  6767 SsdCache.cpp:216] [SSDCA] SSD cache has been shutdown
I20241106 20:09:48.638432  6767 TempDirectoryPath.cpp:29] TempDirectoryPath:: removing all files from /tmp/velox_test_WAwr3b
[  FAILED  ] AsyncDataCacheTest/AsyncDataCacheTest.ssdWriteOptions/2, where GetParam() = 2-byte object <01-01> (202 ms)
```

**Comment by xiaoxmeng** [comment]
@zacw7 can you help take a look at this? thanks!

**Comment by zacw7** [comment]
Fixed in https://github.com/facebookincubator/velox/pull/11491

**Comment by Yuhta** [comment]
This is still happening (under a different config though: `AsyncDataCacheTest/AsyncDataCacheTest.ssdWriteOptions/0`): https://github.com/facebookincubator/velox/actions/runs/12087168636/job/33708043993

**Comment by zacw7** [comment]
let me know if it's still flaky. thanks
