### ISSUE TITLE
Flaky test S3FileSystemRegistrationTest.fileHandle

### ISSUE THREAD

**Issue by jinchengchenghh** [facebookincubator/velox#15304]
### Bug description

CI failed in this PR https://github.com/facebookincubator/velox/pull/15020, but is not related to this PR.
```
[ RUN      ] S3FileSystemRegistrationTest.fileHandle
ERROR Unable to initialize console server: Specified port is already in use
      > Please ensure no other program uses the same address/port
E20251023 16:35:46.941802 81998 Exceptions.h:53] Line: /__w/velox/velox/velox/connectors/hive/storage_adapters/s3fs/S3ReadFile.cpp:72, Function:initialize, Expression:  Failed to get metadata for S3 object due to: 'Network connection'. Path:'s3://data3/test.txt', SDK Error Type:99, HTTP Status Code:-1, S3 Service:'Unknown', Message:'curlCode: 7, Couldn't connect to server', RequestID:''., Source: RUNTIME, ErrorCode: INVALID_STATE
unknown file: Failure
C++ exception with description "Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Failed to get metadata for S3 object due to: 'Network connection'. Path:'s3://data3/test.txt', SDK Error Type:99, HTTP Status Code:-1, S3 Service:'Unknown', Message:'curlCode: 7, Couldn't connect to server', RequestID:''.
Retriable: False
Function: initialize
File: /__w/velox/velox/velox/connectors/hive/storage_adapters/s3fs/S3ReadFile.cpp
Line: 72
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox11filesystems10S3ReadFile4Impl10initializeERKNS1_11FileOptionsE
# 4  _ZN8facebook5velox11filesystems12S3FileSystem15openFileForReadESt17basic_string_viewIcSt11char_traitsIcEERKNS1_11FileOptionsE
# 5  _ZN8facebook5velox19FileHandleGeneratorclERKNS0_13FileHandleKeyEPKNS0_14FilePropertiesEPNS0_11filesystems4File7IoStatsE
# 6  _ZN8facebook5velox13CachedFactoryINS0_13FileHandleKeyENS0_10FileHandleENS0_19FileHandleGeneratorENS0_14FilePropertiesENS0_11filesystems4File7IoStatsENS0_15FileHandleSizerESt8equal_toIS2_ESt4hashIS2_EE8generateERKS2_PKS5_PS8_
# 7  _ZN8facebook5velox11filesystems44S3FileSystemRegistrationTest_fileHandle_Test8TestBodyEv
# 8  0x000000000004fe0c
# 9  _ZN7testing4Test3RunEv
# 10 _ZN7testing8TestInfo3RunEv
# 11 _ZN7testing9TestSuite3RunEv
# 12 _ZN7testing8internal12UnitTestImpl11RunAllTestsEv
# 13 _ZN7testing8UnitTest3RunEv
# 14 main
# 15 __libc_start_call_main
# 16 __libc_start_main
# 17 _start
" thrown in the test body.
I20251023 16:35:47.018715 81998 TempDirectoryPath.cpp:29] TempDirectoryPath:: removing all files from /tmp/velox_test_AI9L6Q
[  FAILED  ] S3FileSystemRegistrationTest.fileHandle (25648 ms)
```

### System information

CI

### Relevant logs

```bash

```

**Comment by mbasmanova** [comment]
@majetideepak Deepak, is this something you could help look into?

CC: @aditi-pandit @pedroerp

**Comment by pedroerp** [comment]
> [@majetideepak](https://github.com/majetideepak) Deepak, is this something you could help look into?
> 
> CC: [@aditi-pandit](https://github.com/aditi-pandit) [@pedroerp](https://github.com/pedroerp)

maybe @JkSelf could help as well?

**Comment by czentgr** [comment]
That is strange. We specifically use test utils to find free ports for the console and API endpoint of the Minio server: https://github.com/facebookincubator/velox/pull/9513
We haven't seen this type of error for a long time. There is perhaps the tiniest time period where a port was free but then it used by the OS before the Minio server can come up and bind it.

**Comment by JkSelf** [comment]
Fixed in https://github.com/facebookincubator/velox/pull/15313.

**Comment by majetideepak** [comment]
The fix in #15313 is not ideal, as it opens room for new flakiness and does not resolve the free port problem.
A better fix is to check if the MinioServer launched properly here and to try again if there is a port conflict instead of erroring out.
https://github.com/facebookincubator/velox/blob/9747b863e4b9a8f525a36b7fb2cc2730bd330be1/velox/connectors/hive/storage_adapters/s3fs/tests/MinioServer.h#L109

**Comment by majetideepak** [comment]
I will open a fix tomorrow if nobody beats me to it.

**Comment by JkSelf** [comment]
@majetideepak I think this problem cannot be completely avoided. Since the free port will be released after allocation [here](https://github.com/facebookincubator/velox/blob/8a5c63e734407e24fd9b977c70e8fab6cfdfa29c/velox/exec/tests/utils/PortUtil.cpp#L48-L50), the port conflict issue will still exist even if we add a retry approach here. Unless we let the server itself allocate a free port when being launched, but in that case, third parties would need to handle this scenario. https://github.com/facebookincubator/velox/pull/15313 can reduce the frequency of free port allocation, ensuring the server is only launched once per test. This can reduce the flakiness risk in certain cases and improve resource usage.

**Comment by majetideepak** [comment]
We don't have data on how often this test failed. If this was the first that happened and reported then the odds of the ports taken away is extremely small. So a retry should help. We use this port utility at a couple of other places and we hardly see this port issue.
If we continue to see this failure after retry, then I agree that #15313 is useful at the risk of ensuring any new tests added must clean up the endpoint completely.

**Comment by JkSelf** [comment]
@majetideepak Thanks for your detailed explanations. Make sense to me.

**Comment by majetideepak** [comment]
Since tests can run concurrently, if we use a single endpoint, each test must also be completely isolated e.g. not using the same bucket. This was the main reason to move away from the single endpoint before.
