### ISSUE TITLE
Failures with Velox debug build

### ISSUE THREAD

**Issue by aditi-pandit** [facebookincubator/velox#2596]
After changes on account of https://github.com/facebookincubator/velox/pull/2383/files#diff-d64ce655bc0bc5dd0e053d5b13f7491c470f97a05b783a1bd0fd9dd262b46cad, some cleanup of protobuf setup was needed for builds to proceed. 

Specifically, I uninstalled (using brew) versions protobuf and protobuf@3 previously used by Velox, and then re-installed protobuf for cmake and builds to proceed.
protoc --version now gives libprotoc 3.21.6 on my system.

Debug builds compile now, but have the following linking errors:
Undefined symbols for architecture x86_64:
  "google::protobuf::internal::InternalMetadata::CheckedDestruct()", referenced from:
      google::protobuf::internal::InternalMetadata::~InternalMetadata() in libvelox_dwio_dwrf_common.a(dwrf-proto-wrapper.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Release builds compile, link and run successfully for the same test.

I found https://stackoverflow.com/questions/73047153/protobuf-ld-undefined-symbol-internalmetadata on the internet that could explain the problem.

Please resolve this issue as it would help unblock testing.

**Comment by mbasmanova** [comment]
@majetideepak @kgpai Deepak, Krishna, would you help take a look?

**Comment by aditi-pandit** [comment]
Seems like we have undone the changes made previously for https://github.com/facebookincubator/velox/issues/2029

**Comment by majetideepak** [comment]
@aditi-pandit is this resolved?

**Comment by kgpai** [comment]
I believe @aditi-pandit  told me this was resolved.

**Comment by aditi-pandit** [comment]
The issue with the debug builds isn't resolved. But please independently check from your side incase this is specific to my setup.

**Comment by aditi-pandit** [comment]
@kgpai : Have you been able to check this on your machine ?

**Comment by kgpai** [comment]
@aditi-pandit On an M1, i could compile velox succesfully with latest changes. I did not have to change anything wrt to setup scripts. If you have some reasonable set of commands to repro I can try that and let you know what I observe.

**Comment by aditi-pandit** [comment]
If this isn't something we see in regular builds then we can close this issue. 

I don't remember the exact steps I have gone through for the setup at this point. So it's counter-productive to have you try to debug them also. I'll try to fix the situation on my machine independently. Thanks for your help.

**Comment by kevinwilfong** [comment]
In case it helps, I ran into the same issue and discovered I had an older version of protobuf in my /usr/local/lib that was getting picked up

Removing all the protobuf libraries from there and allowing Velox to build it again from source resolved it.

Of course, I'm hoping https://github.com/facebookincubator/velox/pull/2979 fixes the build so it picks a consistent version of Protobuf.
