### ISSUE TITLE
Flaky velox_expression_fuzzer_test

### ISSUE THREAD

**Issue by yingsu00** [facebookincubator/velox#6902]
### Description

In several non-related PRs, the velox_expression_fuzzer_test all failed, even when the PR was only to rename a variable.
e.g.
https://app.circleci.com/pipelines/github/facebookincubator/velox/34926/workflows/8fe1e3e1-92b7-4bdf-ad42-8abbd1716fd5/jobs/229225
https://app.circleci.com/pipelines/github/facebookincubator/velox/34919/workflows/ac2aad70-f1cf-40e8-bc52-d12b7a83b1bf/jobs/229189

### Error Reproduction

_build/debug/velox/expression/tests/velox_expression_fuzzer_test --seed ${RANDOM} --enable_variadic_signatures --velox_fuzzer_enable_complex_types --lazy_vector_generation_ratio 0.2 --velox_fuzzer_enable_column_reuse --velox_fuzzer_enable_expression_reuse --max_expression_trees_per_step 2 --retry_with_try --enable_dereference --duration_sec 60 --logtostderr=1 --minloglevel=0 --repro_persist_path=/tmp/fuzzer_repro

### Relevant logs

```bash
I20231004 08:04:32.852838 199542 ExpressionVerifier.cpp:86] Executing expression 0 : 7 elements starting at 21 {[21->15] [15->37] [37->16] [16->28] I'h%Tp."ctBqsJ, [22->26] [26->44] null, null, [24->0] [0->22] [22->28] [28->32] VIQK$#r("2|, [25->2] [2->39] [39->37] [37->49] , ...}
I20231004 08:04:32.852869 199542 ExpressionVerifier.cpp:86] Executing expression 1 : switch("c0",2032-03-03T22:13:08.327976945,"c0",1984-06-28T13:54:38.464569322,array_max(subscript("c1","c2")),2037-09-06T22:08:44.660213362,not("c3"),"c4",cast 572380685 as TIMESTAMP)
E20231004 08:04:32.853734 199542 Exceptions.h:69] Line: ../.././velox/vector/DictionaryVector-inl.h:208, Function:validate, Expression: rawIndices_[i] < dictionaryValues_->size() (9 vs. 0) Dictionary index must be less than base vector's size. Index: 0., Source: RUNTIME, ErrorCode: INVALID_STATE
E20231004 08:04:32.855837 199542 ExpressionVerifier.cpp:176] Common eval: Exceptions other than VeloxUserError are not allowed.
I20231004 08:04:32.857113 199542 ExpressionVerifier.cpp:346] Persisted input: --fuzzer_repro_path /tmp/fuzzer_repro/velox_expressionVerifier_FJaXi3 --input_path /tmp/fuzzer_repro/velox_expressionVerifier_FJaXi3/input_vector --result_path /tmp/fuzzer_repro/velox_expressionVerifier_FJaXi3/result_vector --sql_path /tmp/fuzzer_repro/velox_expressionVerifier_FJaXi3/sql --lazy_column_list_path /tmp/fuzzer_repro/velox_expressionVerifier_FJaXi3/indices_of_lazy_columns --complex_constant_path /tmp/fuzzer_repro/velox_expressionVerifier_FJaXi3/complex_constants
terminate called after throwing an instance of 'facebook::velox::VeloxRuntimeError'
  what():  Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: (9 vs. 0) Dictionary index must be less than base vector's size. Index: 0.
Retriable: False
Expression: rawIndices_[i] < dictionaryValues_->size()
Context: array_max(subscript(c1, c2))
Top-Level Context: switch(c0, 2032-03-03T22:13:08.327976945:TIMESTAMP, c0, 1984-06-28T13:54:38.464569322:TIMESTAMP, array_max(subscript(c1, c2)), 2037-09-06T22:08:44.660213362:TIMESTAMP, not(c3), c4, 1569095-02-02T00:00:00.000000000:TIMESTAMP)
Function: validate
File: ../.././velox/vector/DictionaryVector-inl.h
Line: 208
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxException5State4makeIZNS1_C4EPKcmS5_St17basic_string_viewIcSt11char_traitsIcEES9_S9_S9_bNS1_4TypeES9_EUlRT_E_EESt10shared_ptrIKS2_ESA_SB_
# 2  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 3  _ZN8facebook5velox17VeloxRuntimeErrorC2EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bS7_
# 4  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
# 5  _ZNK8facebook5velox16DictionaryVectorINS0_11ComplexTypeEE8validateERKNS0_21VectorValidateOptionsE
# 6  _ZN8facebook5velox16DictionaryVectorINS0_11ComplexTypeEE16setInternalStateEv
# 7  _ZN8facebook5velox16DictionaryVectorINS0_11ComplexTypeEEC1EPNS0_6memory10MemoryPoolEN5boost13intrusive_ptrINS0_6BufferEEEmSt10shared_ptrINS0_10BaseVectorEESA_RKNS0_17SimpleVectorStatsIS2_EESt8optionalIiESJ_SI_IbESJ_SJ_
# 8  _ZN9__gnu_cxx13new_allocatorIN8facebook5velox16DictionaryVectorINS2_11ComplexTypeEEEE9constructIS5_JRPNS2_6memory10MemoryPoolERN5boost13intrusive_ptrINS2_6BufferEEERmSt10shared_ptrINS2_10BaseVectorEESF_EEEvPT_DpOT0_
# 9  _ZNSt16allocator_traitsISaIN8facebook5velox16DictionaryVectorINS1_11ComplexTypeEEEEE9constructIS4_JRPNS1_6memory10MemoryPoolERN5boost13intrusive_ptrINS1_6BufferEEERmSt10shared_ptrINS1_10BaseVectorEESF_EEEvRS5_PT_DpOT0_
# 10 _ZNSt23_Sp_counted_ptr_inplaceIN8facebook5velox16DictionaryVectorINS1_11ComplexTypeEEESaIS4_ELN9__gnu_cxx12_Lock_policyE2EEC1IJRPNS1_6memory10MemoryPoolERN5boost13intrusive_ptrINS1_6BufferEEERmSt10shared_ptrINS1_10BaseVectorEESH_EEES5_DpOT_
# 11 _ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EEC1IN8facebook5velox16DictionaryVectorINS5_11ComplexTypeEEESaIS8_EJRPNS5_6memory10MemoryPoolERN5boost13intrusive_ptrINS5_6BufferEEERmSt10shared_ptrINS5_10BaseVectorEESH_EEERPT_St20_Sp_alloc_shared_tagIT0_EDpOT1_
# 12 _ZNSt12__shared_ptrIN8facebook5velox16DictionaryVectorINS1_11ComplexTypeEEELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS4_EJRPNS1_6memory10MemoryPoolERN5boost13intrusive_ptrINS1_6BufferEEERmSt10shared_ptrINS1_10BaseVectorEESH_EEESt20_Sp_alloc_shared_tagIT_EDpOT0_
# 13 _ZNSt10shared_ptrIN8facebook5velox16DictionaryVectorINS1_11ComplexTypeEEEEC2ISaIS4_EJRPNS1_6memory10MemoryPoolERN5boost13intrusive_ptrINS1_6BufferEEERmS_INS1_10BaseVectorEESF_EEESt20_Sp_alloc_shared_tagIT_EDpOT0_
# 14 _ZSt15allocate_sharedIN8facebook5velox16DictionaryVectorINS1_11ComplexTypeEEESaIS4_EJRPNS1_6memory10MemoryPoolERN5boost13intrusive_ptrINS1_6BufferEEERmSt10shared_ptrINS1_10BaseVectorEESD_EESG_IT_ERKT0_DpOT1_
# 15 _ZSt11make_sharedIN8facebook5velox16DictionaryVectorINS1_11ComplexTypeEEEJRPNS1_6memory10MemoryPoolERN5boost13intrusive_ptrINS1_6BufferEEERmSt10shared_ptrINS1_10BaseVectorEESC_EESF_IT_EDpOT0_
# 16 _ZN8facebook5veloxL13addDictionaryILNS0_8TypeKindE30EEESt10shared_ptrINS0_10BaseVectorEEN5boost13intrusive_ptrINS0_6BufferEEES9_mS5_
# 17 _ZZZN8facebook5velox10BaseVector16wrapInDictionaryEN5boost13intrusive_ptrINS0_6BufferEEES5_iSt10shared_ptrIS1_EENKUlvE_clEvENKUlvE_clEv
# 18 _ZZN8facebook5velox10BaseVector16wrapInDictionaryEN5boost13intrusive_ptrINS0_6BufferEEES5_iSt10shared_ptrIS1_EENKUlvE_clEv
# 19 _ZN8facebook5velox10BaseVector16wrapInDictionaryEN5boost13intrusive_ptrINS0_6BufferEEES5_iSt10shared_ptrIS1_E
# 20 _ZN8facebook5velox12_GLOBAL__N_116VectorLoaderWrap25makeEncodingPreservedCopyERNS0_17SelectivityVectorEi
# 21 _ZN8facebook5velox12_GLOBAL__N_116VectorLoaderWrap12loadInternalEN5folly5RangeIPKiEEPNS0_9ValueHookEiPSt10shared_ptrINS0_10BaseVectorEE
# 22 _ZN8facebook5velox12VectorLoader4loadEN5folly5RangeIPKiEEPNS0_9ValueHookEiPSt10shared_ptrINS0_10BaseVectorEE
# 23 _ZNK8facebook5velox10LazyVector4loadEN5folly5RangeIPKiEEPNS0_9ValueHookE
# 24 _ZN8facebook5velox10LazyVector20ensureLoadedRowsImplERKSt10shared_ptrINS0_10BaseVectorEERNS0_13DecodedVectorERKNS0_17SelectivityVectorERS9_
# 25 _ZN8facebook5velox10LazyVector16ensureLoadedRowsERKSt10shared_ptrINS0_10BaseVectorEERKNS0_17SelectivityVectorERNS0_13DecodedVectorERS7_
# 26 _ZN8facebook5velox4exec7EvalCtx17ensureFieldLoadedEiRKNS0_17SelectivityVectorE
# 27 _ZN8facebook5velox4exec4Expr4evalERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEEPKNS1_7ExprSetE
# 28 _ZN8facebook5velox4exec10SwitchExpr15evalSpecialFormERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 29 _ZN8facebook5velox4exec4Expr24evalSpecialFormWithStatsERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 30 _ZN8facebook5velox4exec4Expr11evalAllImplERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 31 _ZN8facebook5velox4exec4Expr7evalAllERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 32 _ZN8facebook5velox4exec4Expr13evalWithNullsERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 33 _ZN8facebook5velox4exec4Expr13evalEncodingsERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEE
# 34 _ZN8facebook5velox4exec4Expr4evalERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt10shared_ptrINS0_10BaseVectorEEPKNS1_7ExprSetE
# 35 _ZN8facebook5velox4exec7ExprSet4evalEiibRKNS0_17SelectivityVectorERNS1_7EvalCtxERSt6vectorISt10shared_ptrINS0_10BaseVectorEESaISB_EE
# 36 _ZN8facebook5velox4exec7ExprSet4evalERKNS0_17SelectivityVectorERNS1_7EvalCtxERSt6vectorISt10shared_ptrINS0_10BaseVectorEESaISB_EE
# 37 _ZN8facebook5velox4test18ExpressionVerifier6verifyERKSt6vectorISt10shared_ptrIKNS0_4core10ITypedExprEESaIS8_EERKS4_INS0_9RowVectorEEOS4_INS0_10BaseVectorEEbS3_IiSaIiEE
# 38 _ZN8facebook5velox4test16ExpressionFuzzer12retryWithTryESt6vectorISt10shared_ptrIKNS0_4core10ITypedExprEESaIS8_EERKS4_INS0_9RowVectorEERKS4_INS0_10BaseVectorEERKS3_IiSaIiEE
# 39 _ZN8facebook5velox4test16ExpressionFuzzer2goEv
# 40 _ZN8facebook5velox4test16expressionFuzzerESt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIPKNS0_4exec17FunctionSignatureESaISD_EESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SF_EEEm
# 41 _ZN12FuzzerRunner12runFromGtestERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEmRKSt13unordered_setIS5_St4hashIS5_ESt8equal_toIS5_ESaIS5_EES7_
# 42 _ZN12FuzzerRunner3runERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEmRKSt13unordered_setIS5_St4hashIS5_ESt8equal_toIS5_ESaIS5_EES7_
# 43 main
# 44 __libc_start_main
# 45 _start

*** Aborted at 1696406673 (Unix time, try 'date -d @1696406673') ***
*** Signal 6 (SIGABRT) (0x30b76) received by PID 199542 (pthread TID 0x7f52e9fe7580) (linux TID 199542) (maybe from PID 199542, UID 0) (code: -6), stack trace: ***
(error retrieving stack trace)
/bin/bash: line 16: 199542 Aborted                 (core dumped) _build/debug/velox/expression/tests/velox_expression_fuzzer_test --seed ${RANDOM} --enable_variadic_signatures --velox_fuzzer_enable_complex_types --lazy_vector_generation_ratio 0.2 --velox_fuzzer_enable_column_reuse --velox_fuzzer_enable_expression_reuse --max_expression_trees_per_step 2 --retry_with_try --enable_dereference --duration_sec 60 --logtostderr=1 --minloglevel=0 --repro_persist_path=/tmp/fuzzer_repro

Exited with code exit status 134
```

**Comment by laithsakka** [comment]
how recent are those, yeh its not flakey  but catching same bugs over and over, we shall have landed the big fixes yesterday will take a look today

**Comment by laithsakka** [comment]
Fixed on master

**Comment by yingsu00** [comment]
@laithsakka Thank you for your quick fix. I still see the error in https://app.circleci.com/pipelines/github/facebookincubator/velox/35097/workflows/7482796e-0628-4465-a720-a361a2aeded4/jobs/230658 , is it a different issue?

**Comment by laithsakka** [comment]
this is different and was fixed here, 
https://github.com/facebookincubator/velox/issues/6918
but there are still other issues, can you file new issues for each that you see with a different message:
Ex: the messages above are
on: y >= 0 
and
rawIndices_[i] < dictionaryValues_->size()

FYI there is a new issue 
 rawOffsets_[i] + rawSizes_[i] - 1 < minChildVectorSiz

**Comment by laithsakka** [comment]
@yingsu00 we have a set of issues that will appear sequentially as we solve them, 
this is because the signal was off for a while. so new diffs my have introduced bugs that were not cought like the one above
we are working to get the signals clean again ..
hopefully soon!

**Comment by yingsu00** [comment]
THanks @laithsakka for the information!
