### ISSUE TITLE
‘scm_timestamping’ does not name a type

### ISSUE THREAD

**Issue by Swthaochen** [facebookincubator/velox#7714]
### Problem description

I have some problems when build velox, it may be related with folly:
```
../folly/io/async/AsyncSocket.cpp:216:7: error: ‘scm_timestamping’ does not name a type; did you mean ‘SN_ad_timeStamping’?
  216 | const scm_timestamping* FOLLY_NULLABLE
      |       ^~~~~~~~~~~~~~~~
      |       SN_ad_timeStamping
../folly/io/async/AsyncSocket.cpp: In member function ‘folly::Optional<folly::AsyncTransport::ByteEvent> folly::AsyncSocket::ByteEventHelper::processCmsg(const cmsghdr&, size_t)’:
../folly/io/async/AsyncSocket.cpp:506:27: error: ‘cmsgToScmTimestamping’ was not declared in this scope
  506 |   } else if (auto scmTs = cmsgToScmTimestamping(cmsg)) {
      |                           ^~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```
so what's wrong with this ?

### System information

centos 7

**Comment by mbasmanova** [comment]
CC: @kgpai @assignUser @majetideepak

**Comment by majetideepak** [comment]
@Swthaochen This looks like a known Folly issue on CentOS7 https://github.com/facebook/folly/issues/1729
Unfortunately, a fix does not seem to exist.

**Comment by assignUser** [comment]
I came across this when looking at the conda build, the folly feedstock solves it with:
````sh
# Resolves error: 'scm_timestamping' does not name a type
export CXXFLAGS="$CXXFLAGS -DFOLLY_HAVE_SO_TIMESTAMPING=0"
```

**Comment by assignUser** [comment]
I assume issue is solved, If not feel free to reopen!

**Comment by dingxin-tech** [comment]
I've add `-DFOLLY_HAVE_SO_TIMESTAMPING=0` to CXXFLAGS , however still encountered the same error. 

Has anyone solved this problem?

cmake warning
```#cmake -Wno-dev -B_build -GNinja -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_CXX_STANDARD=17 '' '' '-DCMAKE_CXX_FLAGS=-march=native -std=c++17 -mno-avx512f -mbmi2 ' -DBUILD_TESTING=OFF -DBUILD_TESTS=OFF -DFOLLY_HAVE_INT128_T=ON -DFOLLY_HAVE_SO_TIMESTAMPING=0
-- other platform:
-- Found gflags from package config /usr/local/lib64/cmake/gflags/gflags-config.cmake
-- Found gflags as a dependency of glog::glog, include=/usr/local/include, libs=gflags_shared
-- Found libevent: /usr/lib64/libevent.so
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
-- Found LZ4: /usr/lib64/liblz4.so
-- Found Zstd: /usr/lib64/libzstd.so
-- Could NOT find LIBIBERTY (missing: LIBIBERTY_LIBRARY LIBIBERTY_INCLUDE_DIR)
-- Could NOT find LIBAIO (missing: LIBAIO_LIBRARY LIBAIO_INCLUDE_DIR)
-- Could NOT find LIBURING (missing: LIBURING_LIBRARY LIBURING_INCLUDE_DIR)
-- Could NOT find LIBSODIUM (missing: LIBSODIUM_LIBRARY LIBSODIUM_INCLUDE_DIR)
-- Could NOT find LIBUNWIND (missing: LIBUNWIND_LIBRARY LIBUNWIND_INCLUDE_DIR)
-- Setting FOLLY_USE_SYMBOLIZER: ON
-- Setting FOLLY_HAVE_ELF: 1
-- Setting FOLLY_HAVE_DWARF: TRUE
-- GCC does not have support for C++ coroutines, disabling Folly coroutine support.
-- arch  matches x86_64, building SSE4.2 version of base64
-- compiler has flag pclmul, setting compile flag for /tmp/velox-deps/folly/folly/hash/detail/ChecksumDetail.cpp;/tmp/velox-deps/folly/folly/hash/detail/Crc32CombineDetail.cpp;/tmp/velox-deps/folly/folly/hash/detail/Crc32cDetail.cpp
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    FOLLY_HAVE_SO_TIMESTAMPING


-- Build files have been written to: /tmp/velox-deps/folly/_build
```

build error
```
/folly/io/async/AsyncSocket.cpp:216:7: error: ‘scm_timestamping’ does not name a type; did you mean ‘SN_ad_timeStamping’?
```

**Comment by assignUser** [comment]
@dingxin-tech You didn't actually add it to the cxx flags but rather added it as a cmake variable: 
```
CMake Warning:
  Manually-specified variables were not used by the project:

    FOLLY_HAVE_SO_TIMESTAMPING
```
you have to add it in the quotes of`-DCMAKE_CXX_FLAGS='...'`

**Comment by dingxin-tech** [comment]
> @dingxin-tech You didn't actually add it to the cxx flags but rather added it as a cmake variable:
> 
> ```
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     FOLLY_HAVE_SO_TIMESTAMPING
> ```
> 
> you have to add it in the quotes of`-DCMAKE_CXX_FLAGS='...'`

Yes, you are right, after adding it, the error will not be reported. 
Thank you for your reply.
